# Generated by Django 5.2 on 2025-04-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='discounted_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='game_title',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='tag',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='tag_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='type',
            field=models.CharField(blank=True, choices=[('density', '할인율 분포'), ('tag', '태그별 통계'), ('value', '가성비 순위')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='value_score',
            field=models.FloatField(default=0),
        ),
    ]
