# Generated by Django 5.2 on 2025-04-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
