# Generated by Django 5.2 on 2025-04-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_alter_game_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.AddField(
            model_name='stats',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
