# Generated by Django 5.2 on 2025-04-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_stats_discounted_price_stats_game_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='original_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='discount_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='discount_rate_density',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='game_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='type',
            field=models.CharField(choices=[('discount_kde', '할인률 분포'), ('tag', '태그별 게임 수'), ('value', '가성비 순위'), ('price', '원가 vs 할인가'), ('bubble', '리뷰 vs 할인률')], default='unknown', max_length=20),
            preserve_default=False,
        ),
    ]
