# Generated by Django 5.2 on 2025-04-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_stats_original_price_alter_stats_discount_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='discount_rate',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='discount_rate_density',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='game_title',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='review_count',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='tag_count',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='type',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='value_score',
        ),
        migrations.AddField(
            model_name='stats',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
